### ISSUE TITLE
As a User I need to record Contact Tracing

### ISSUE THREAD

**Issue by fredkingham** [openhealthcare/uclp-tb#18]
So that I can follow up with contacts and reduce the spread of TB.

Sub Stories: 

As a User I need to record the Infectivity Risk of a TB Patient
So that I can assess how to proceed with mitigating that risk

As a User I need to record the contact details, some demographics of Contacts
So that I can follow up with them and make sure they get tested for TB

Acceptance Criteria 

- [ ] Pathway which I can access from the TB detail View
- [ ] Save many new "Contacts" and have these turn into new patients
- [ ] Record infectivity risks
